#pragma once

// Parent Includes
#include "Subsystems/GameInstanceSubsystem.h"

// Engine Includes
#include "Tickable.h"

// Generated Includes
#include "Developer_Subsystem_Notification.generated.h"


// ---------------------------------
// --- Structs
// ---------------------------------

USTRUCT(BlueprintType)
struct FNotificationData
{
	GENERATED_BODY()

	/* generated by the subsystem when notification is added */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString ID;

	/* included in delegate when notification ends */
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	TArray<FString> Strings;

	/* duration of notification */
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	double DurationSeconds;

	/* if true; notification is queued and waits until no active notifications before occuring 
	*	queued notifications occur in order they were added
	*/
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	bool bQueued;

	FNotificationData()
	{
		ID = TEXT("");
		DurationSeconds = 0;
		bQueued = false;
	}

	FNotificationData(const FString& message, double durationSeconds, bool bQueue)
	{
		Strings.Add(message);

		DurationSeconds = durationSeconds;

		bQueued = bQueue;
	}
};

UCLASS()
class VH_DEVELOPER_API UDeveloper_Subsystem_Notification : public UGameInstanceSubsystem, public FTickableGameObject
{
	GENERATED_BODY()


	// ---------------------------------
	// --- Delegates
	// ---------------------------------

private:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FNotificationDelegate, const FNotificationData&, notificationData);


	// ---------------------------------
	// --- Variables
	// ---------------------------------

public:
	UPROPERTY(BlueprintAssignable, BlueprintReadWrite)
	FNotificationDelegate OnAddNotification;

	UPROPERTY(BlueprintAssignable, BlueprintReadWrite)
	FNotificationDelegate OnShowNotification;

	UPROPERTY(BlueprintAssignable, BlueprintReadWrite)
	FNotificationDelegate OnEndNotification;

private:
	UPROPERTY()
	TMap<FString, FNotificationData> Notifications;

	/* maps notificationID to remaining duration */
	TMap<FString, double> ActiveNotifications;

	TArray<FString> QueuedNotifications;


	// ---------------------------------
	// --- Constructors
	// ---------------------------------

public:
	UDeveloper_Subsystem_Notification();


	// ---------------------------------
	// --- FTickableGameObject
	// ---------------------------------

public:
	virtual bool IsTickable() const override;
	
	virtual void Tick(float deltaSeconds) override;
	
	virtual TStatId GetStatId() const override;


	// ---------------------------------
	// --- Static Functions
	// ---------------------------------

public:
	static UDeveloper_Subsystem_Notification* Get();


	// ---------------------------------
	// --- API
	// ---------------------------------

public:
	/* \brief Adds a notification; displays immediately for durationSeconds
	*  \param notificationData Data for notification
	*  \return ID of notification
	*/
	UFUNCTION(BlueprintCallable)
	FString AddNotification(FNotificationData notificationData);

	/* \brief Ends a notification; optionally calling OnEndNotification is notification is currently shown
	*  \param notificationID ID of notification to cancel
	*  \param bBroadcast If true, broadcasts OnEndNotification
	*  \return True if ID exists
	*/
	UFUNCTION(BlueprintCallable)
	bool EndNotification(const FString& notificationID, bool bBroadcast);
};
